spring:
  config:
    activate:
      on-profile: dev # dev 프로파일

  datasource:
    url: jdbc:mariadb://211.110.44.79:3306/ezylab_dev
    username: itadmin #사용자
    password: gthkds!83! #비밀번호
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: DEBUG # 전체 애플리케이션 기본 로그 레벨
    sun.rmi: INFO
    sun.rmi.transport.tcp: INFO
    javax.management.remote.rmi: INFO
    org.apache.coyote.http11: INFO
    org.springframework: WARN # 스프링 관련 로그 경고(WARN) 이상만 출력
    bon.bon_jujitsu: DEBUG # 특정 패키지(bon.bon_jujitsu) 로그 디버그(DEBUG) 모드 활성화
    org.springframework.web: DEBUG # Spring Web 로그 디버그(DEBUG) 모드 활성화
    org.springframework.jdbc: DEBUG # Spring JDBC 로그 디버그(DEBUG) 모드 활성화
    org.springframework.transaction: DEBUG # Spring 트랜잭션 로그 디버그(DEBUG) 모드 활성화

filepath: /uploads/images/
