spring:
  config:
    activate:
      on-profile: dev  # dev 프로파일

  datasource:
    url: jdbc:mariadb://211.110.44.79:3306/ezylab_dev
    username: itadmin #사용자
    password: gthkds!83! #비밀번호
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

filepath: /uploads/images/