spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://211.110.44.28:3306/ezylab_prod
    username: itadmin #사용자
    password: kdsgth!84! #비밀번호
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

filepath:
  image: /data/uploads/ezylab_prod/
  attachment: /data/uploads/ezylab_prod/attachments/
